import { Heart, Brain, Sparkles, Lightbulb, Shield, Zap, Leaf, Sun, Moon, Flame, Compass, Smile } from "lucide-react"
import type { Intention } from "./types"

export const intentions: Intention[] = [
  {
    id: "cura",
    name: "Cura",
    description: "Promove a cura física, emocional e energética, restaurando o equilíbrio natural do corpo e da mente.",
    affirmation: "Eu me abro para a energia de cura que flui através de mim, restaurando meu corpo, mente e espírito.",
    icon: <Heart className="h-5 w-5 text-pink-400" />,
    fractalImage: "/images/intentions/fractal-healing.jpg",
    geometryImage: "/images/intentions/geometry-healing.svg",
    videoUrl: "/videos/healing-intention.mp4",
    color: "pink",
  },
  {
    id: "foco",
    name: "Foco",
    description:
      "Aumenta a concentração e clareza mental, ajudando a manter o foco em tarefas e objetivos importantes.",
    affirmation: "Minha mente está clara e focada. Eu direciono minha energia para o que realmente importa hoje.",
    icon: <Brain className="h-5 w-5 text-blue-400" />,
    fractalImage: "/images/intentions/fractal-focus.jpg",
    geometryImage: "/images/intentions/geometry-focus.svg",
    videoUrl: "/videos/focus-intention.mp4",
    color: "blue",
  },
  {
    id: "clareza",
    name: "Clareza",
    description: "Traz nitidez de pensamento e visão, dissipando confusão e permitindo decisões mais conscientes.",
    affirmation: "Eu vejo com clareza o caminho à minha frente. Minhas decisões são guiadas pela sabedoria interior.",
    icon: <Sparkles className="h-5 w-5 text-cyan-400" />,
    fractalImage: "/images/intentions/fractal-clarity.jpg",
    geometryImage: "/images/intentions/geometry-clarity.svg",
    videoUrl: "/videos/clarity-intention.mp4",
    color: "cyan",
  },
  {
    id: "inspiracao",
    name: "Inspiração",
    description: "Estimula a criatividade e novas ideias, conectando-o com sua fonte interior de inspiração.",
    affirmation: "Estou aberto a receber ideias criativas e inspiração divina em tudo que faço hoje.",
    icon: <Lightbulb className="h-5 w-5 text-yellow-400" />,
    fractalImage: "/images/intentions/fractal-inspiration.jpg",
    geometryImage: "/images/intentions/geometry-inspiration.svg",
    videoUrl: "/videos/inspiration-intention.mp4",
    color: "yellow",
  },
  {
    id: "protecao",
    name: "Proteção",
    description: "Cria um escudo energético que protege contra energias negativas e influências externas indesejadas.",
    affirmation: "Estou protegido por uma luz divina. Nada que não sirva ao meu bem maior pode me afetar.",
    icon: <Shield className="h-5 w-5 text-indigo-400" />,
    fractalImage: "/images/intentions/fractal-protection.jpg",
    geometryImage: "/images/intentions/geometry-protection.svg",
    videoUrl: "/videos/protection-intention.mp4",
    color: "indigo",
  },
  {
    id: "energia",
    name: "Energia",
    description:
      "Revitaliza o corpo e a mente, aumentando os níveis de energia e disposição para as atividades diárias.",
    affirmation: "Meu corpo está cheio de vitalidade e energia. Tenho força e disposição para realizar tudo hoje.",
    icon: <Zap className="h-5 w-5 text-orange-400" />,
    fractalImage: "/images/intentions/fractal-energy.jpg",
    geometryImage: "/images/intentions/geometry-energy.svg",
    videoUrl: "/videos/energy-intention.mp4",
    color: "orange",
  },
  {
    id: "paz",
    name: "Paz",
    description: "Cultiva um estado de tranquilidade interior e harmonia, independente das circunstâncias externas.",
    affirmation: "Eu sou paz. Permaneço centrado e tranquilo em todas as situações que encontro hoje.",
    icon: <Leaf className="h-5 w-5 text-green-400" />,
    fractalImage: "/images/intentions/fractal-peace.jpg",
    geometryImage: "/images/intentions/geometry-peace.svg",
    videoUrl: "/videos/peace-intention.mp4",
    color: "green",
  },
  {
    id: "abundancia",
    name: "Abundância",
    description: "Atrai prosperidade e plenitude em todas as áreas da vida, expandindo a consciência de abundância.",
    affirmation: "Eu vivo em um universo abundante. Estou aberto a receber todas as bênçãos que fluem para mim hoje.",
    icon: <Sun className="h-5 w-5 text-amber-400" />,
    fractalImage: "/images/intentions/fractal-abundance.jpg",
    geometryImage: "/images/intentions/geometry-abundance.svg",
    videoUrl: "/videos/abundance-intention.mp4",
    color: "amber",
  },
  {
    id: "relaxamento",
    name: "Relaxamento",
    description: "Promove o alívio do estresse e tensão, induzindo um estado de relaxamento profundo e restaurador.",
    affirmation: "Eu libero toda tensão e estresse. Meu corpo e mente estão completamente relaxados e em paz.",
    icon: <Moon className="h-5 w-5 text-purple-400" />,
    fractalImage: "/images/intentions/fractal-relaxation.jpg",
    geometryImage: "/images/intentions/geometry-relaxation.svg",
    videoUrl: "/videos/relaxation-intention.mp4",
    color: "purple",
  },
  {
    id: "transformacao",
    name: "Transformação",
    description: "Facilita mudanças positivas e crescimento pessoal, apoiando a evolução e o desenvolvimento interior.",
    affirmation: "Eu abraço a mudança como uma oportunidade de crescimento. Estou me transformando a cada momento.",
    icon: <Flame className="h-5 w-5 text-red-400" />,
    fractalImage: "/images/intentions/fractal-transformation.jpg",
    geometryImage: "/images/intentions/geometry-transformation.svg",
    videoUrl: "/videos/transformation-intention.mp4",
    color: "red",
  },
  {
    id: "intuicao",
    name: "Intuição",
    description: "Fortalece a conexão com sua sabedoria interior e percepção intuitiva, guiando suas decisões.",
    affirmation: "Eu confio na minha intuição. Minha sabedoria interior me guia para as escolhas certas.",
    icon: <Compass className="h-5 w-5 text-teal-400" />,
    fractalImage: "/images/intentions/fractal-intuition.jpg",
    geometryImage: "/images/intentions/geometry-intuition.svg",
    videoUrl: "/videos/intuition-intention.mp4",
    color: "teal",
  },
  {
    id: "gratidao",
    name: "Gratidão",
    description:
      "Cultiva um estado de apreciação e reconhecimento pelas bênçãos em sua vida, atraindo mais positividade.",
    affirmation: "Meu coração está cheio de gratidão por todas as bênçãos em minha vida. Eu reconheço e agradeço.",
    icon: <Smile className="h-5 w-5 text-emerald-400" />,
    fractalImage: "/images/intentions/fractal-gratitude.jpg",
    geometryImage: "/images/intentions/geometry-gratitude.svg",
    videoUrl: "/videos/gratitude-intention.mp4",
    color: "emerald",
  },
]
